on:
  schedule:
    - cron: 0 12 * * SUN
  workflow_dispatch:

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ['1.22.x']
    defaults:
      run:
        working-directory: instapaper-backup-go
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      # You can test your matrix by printing the current Go version
      - name: Display Go version
        run: go version

      - name: Install dependencies
        run: |
          go get .

      - name: Build
        run: go build -v 

      - name: Run
        run: ./instapaper-backup-go
        env:
          INSTAPAPER_KEY: ${{ secrets.INSTAPAPER_KEY }}
          INSTAPAPER_SECRET: ${{ secrets.INSTAPAPER_SECRET }}
          INSTAPAPER_USERNAME: ${{ secrets.INSTAPAPER_USERNAME }}
          INSTAPAPER_PASSWORD: ${{ secrets.INSTAPAPER_PASSWORD }}

      - name: Commit and push changes
        run: |
          cd ..
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add .
          git diff --quiet && git diff --staged --quiet || (git commit -m "Auto-update Instapaper backup [skip ci]" && git push)

      - name: Cleanup
        run: rm instapaper-backup-go

